# Generated by Django 3.1 on 2020-08-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
